import pandas as pd
import numpy as np
import torch
from torch_geometric.data import HeteroData
from transformers import AutoTokenizer, AutoModel
import tqdm
import json

def impute_missing(df, text_col, title_col, year_col, default_year=2020):
    """Safely imputes missing text fields and years."""
    df[year_col] = df[year_col].fillna(default_year)
    df[text_col] = df[text_col].fillna(df[title_col])
    df[text_col] = df[text_col].fillna("No abstract available")
    df[title_col] = df[title_col].fillna("Unknown Title")
    return df

def main():
    print("Loading CLEANED datasets...")
    # These were generated by clean_hop_data.py
    hop0 = pd.read_csv("data/cleaned/hop0_v2.csv")
    hop1 = pd.read_csv("data/cleaned/hop1_v2.csv")
    hop2 = pd.read_csv("data/cleaned/hop2_v2.csv")

    print("Calculating robust temporal defaults...")
    combined_years = pd.concat([hop0['year'], hop1['hop1_year'], hop2['hop2_year']]).dropna()
    global_median_year = int(combined_years.median()) if not combined_years.empty else 2018
    
    print("Imputing missing values...")
    hop0 = impute_missing(hop0, "abstract", "title", "year", default_year=global_median_year)
    hop1 = impute_missing(hop1, "hop1_abstract", "hop1_title", "hop1_year", default_year=global_median_year)
    hop2 = impute_missing(hop2, "hop2_abstract", "hop2_title", "hop2_year", default_year=global_median_year)

    print("Collecting unique papers and tracking layers...")
    papers = {}
    
    # Layer 0: The Seeds (Foundational Roots)
    for _, row in hop0.iterrows():
        pid = row["source_paper_id"]
        papers[pid] = {"title": row["title"], "abstract": row["abstract"], "year": row["year"], "layer": 0}
    
    # Layer 1: Papers citing Hop-0 (Expansion)
    for _, row in hop1.iterrows():
        pid = row["hop1_id"]
        if pid not in papers:
            papers[pid] = {"title": row["hop1_title"], "abstract": row["hop1_abstract"], "year": row["hop1_year"], "layer": 1}
        else:
            # If a seed (Layer 0) is discovered citing another seed, we keep it as Layer 0
            if papers[pid]["layer"] > 1: papers[pid]["layer"] = 1
            
        h0_pid = row["hop0_id"]
        if h0_pid not in papers:
            papers[h0_pid] = {"title": "Unknown Title", "abstract": "No abstract available", "year": global_median_year, "layer": 0}

    # Layer 2: Papers citing Hop-1 (Impact Ring)
    for _, row in hop2.iterrows():
        pid = row["hop2_id"]
        if pid not in papers:
            papers[pid] = {"title": row["hop2_title"], "abstract": row["hop2_abstract"], "year": row["hop2_year"], "layer": 2}
        else:
            # If a paper was already Layer 0 or 1, we don't 'demote' it to Layer 2
            pass

    paper_ids = list(papers.keys())
    paper2idx = {pid: i for i, pid in enumerate(paper_ids)}
    num_papers = len(paper_ids)
    print(f"Total unique papers (all layers): {num_papers}")

    print("Loading SciBERT...")
    tokenizer = AutoTokenizer.from_pretrained("allenai/scibert_scivocab_uncased")
    model = AutoModel.from_pretrained("allenai/scibert_scivocab_uncased")
    device = torch.device("mps" if torch.backends.mps.is_available() else "cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")
    model = model.to(device).eval()

    embeddings = []
    batch_size = 16
    texts = [str(papers[pid]["title"]) + " [SEP] " + str(papers[pid]["abstract"]) for pid in paper_ids]
    
    print("Computing embeddings...")
    for i in tqdm.tqdm(range(0, len(texts), batch_size)):
        batch_text = texts[i:i+batch_size]
        inputs = tokenizer(batch_text, padding=True, truncation=True, max_length=512, return_tensors="pt").to(device)
        with torch.no_grad():
            outputs = model(**inputs)
            emb = outputs.last_hidden_state[:, 0, :].cpu()
            embeddings.append(emb)

    embeddings = torch.cat(embeddings, dim=0)
    data = HeteroData()
    data['paper'].x = embeddings
    data['author'].x = torch.zeros(0, 128)

    print("Merging and Deduplicating Edges...")
    # Keep the citation_text column so we can embed it
    h1_edges = hop1[['hop1_id', 'hop0_id', 'intent_label', 'citation_text']].copy().rename(
        columns={'hop1_id': 'src', 'hop0_id': 'dst'}
    )
    h2_edges = hop2[['hop2_id', 'hop1_id', 'citation_text']].copy().rename(
        columns={'hop2_id': 'src', 'hop1_id': 'dst'}
    )
    h2_edges['intent_label'] = -1
    
    # Fill missing citation contexts with a placeholder so SciBERT doesn't crash
    h1_edges['citation_text'] = h1_edges['citation_text'].fillna("Citation context missing.")
    h2_edges['citation_text'] = h2_edges['citation_text'].fillna("Citation context missing.")

    all_edges_df = pd.concat([h1_edges, h2_edges]).drop_duplicates(subset=['src', 'dst'], keep='first')

    # cites_src, cites_dst, edge_attrs, delta_ts, intent_labels, label_masks = [], [], [], [], [], []
    # intent_map = {"background": 0, "method": 1, "result": 2}
    
    # for _, row in all_edges_df.iterrows():
    #     src, dst = row["src"], row["dst"]
    #     if src in paper2idx and dst in paper2idx:
    #         cites_src.append(paper2idx[src])
    #         cites_dst.append(paper2idx[dst])
    #         edge_attrs.append(embeddings[paper2idx[src]])
    #         label_str = str(row["intent_label"]).lower()
    #         if label_str in intent_map:
    #             intent_labels.append(intent_map[label_str])
    #             label_masks.append(True)
    #         else:
    #             intent_labels.append(-1); label_masks.append(False)
    #         try:
    #             src_yr, dst_yr = int(float(papers[src]["year"])), int(float(papers[dst]["year"]))
    #             if dst_yr >= src_yr: dst_yr = src_yr - 1
    #             delta_ts.append(max(1, src_yr - dst_yr))
    #         except: delta_ts.append(1)
            
    # data['paper', 'cites', 'paper'].edge_index = torch.tensor([cites_src, cites_dst], dtype=torch.long)
    # data['paper', 'cites', 'paper'].edge_attr = torch.stack(edge_attrs)
    # data['paper', 'cites', 'paper'].delta_t = torch.tensor(delta_ts, dtype=torch.float).unsqueeze(1)
    # data['paper', 'cites', 'paper'].intent_label = torch.tensor(intent_labels, dtype=torch.long)
    # data['paper', 'cites', 'paper'].train_mask = torch.tensor(label_masks, dtype=torch.bool)
    # data['author', 'writes', 'paper'].edge_index = torch.empty((2, 0), dtype=torch.long)

    cites_src, cites_dst, delta_ts, intent_labels, label_masks = [], [], [], [], []
    valid_citation_texts = []
    intent_map = {"background": 0, "method": 1, "result": 2}
    
    for _, row in all_edges_df.iterrows():
        src, dst = row["src"], row["dst"]
        if src in paper2idx and dst in paper2idx:
            cites_src.append(paper2idx[src])
            cites_dst.append(paper2idx[dst])
            valid_citation_texts.append(str(row["citation_text"])) # Save the text to be embedded
            
            label_str = str(row["intent_label"]).lower()
            if label_str in intent_map:
                intent_labels.append(intent_map[label_str])
                label_masks.append(True)
            else:
                intent_labels.append(-1); label_masks.append(False)
            try:
                src_yr, dst_yr = int(float(papers[src]["year"])), int(float(papers[dst]["year"]))
                if dst_yr >= src_yr: dst_yr = src_yr - 1
                delta_ts.append(max(1, src_yr - dst_yr))
            except: 
                delta_ts.append(1)

    print("Computing EDGE embeddings from citation contexts...")
    edge_embeddings = []
    # Run the citation sentences through SciBERT
    for i in tqdm.tqdm(range(0, len(valid_citation_texts), batch_size)):
        batch_text = valid_citation_texts[i:i+batch_size]
        inputs = tokenizer(batch_text, padding=True, truncation=True, max_length=512, return_tensors="pt").to(device)
        with torch.no_grad():
            outputs = model(**inputs)
            # Use the [CLS] token representation for the edge feature
            emb = outputs.last_hidden_state[:, 0, :].cpu()
            edge_embeddings.append(emb)
            
    edge_embeddings = torch.cat(edge_embeddings, dim=0)

    # Now we attach the true semantic context to the graph object
    data['paper', 'cites', 'paper'].edge_index = torch.tensor([cites_src, cites_dst], dtype=torch.long)
    data['paper', 'cites', 'paper'].edge_attr = edge_embeddings  # <--- THIS IS THE CRITICAL FIX
    data['paper', 'cites', 'paper'].delta_t = torch.tensor(delta_ts, dtype=torch.float).unsqueeze(1)
    data['paper', 'cites', 'paper'].intent_label = torch.tensor(intent_labels, dtype=torch.long)
    data['paper', 'cites', 'paper'].train_mask = torch.tensor(label_masks, dtype=torch.bool)
    data['author', 'writes', 'paper'].edge_index = torch.empty((2, 0), dtype=torch.long)

    print("\n🧐 COMMENCING NETWORK SANITY CHECK...")
    labeled_count = data['paper', 'cites', 'paper'].train_mask.sum().item()
    total_edges = data['paper', 'cites', 'paper'].edge_index.shape[1]
    print(f"|--- Total Unique Papers: {num_papers}")
    print(f"|--- Total Citation Edges: {total_edges}")
    print(f"|--- Layer Distribution: {pd.Series([p['layer'] for p in papers.values()]).value_counts().to_dict()}")
    print(f"✅ Sanity Check Passed.\n")

    print("📦 Exporting Optimized Dashboard Files...")
    h1_ctx = hop1[['hop1_id', 'hop0_id', 'citation_text']].copy().rename(columns={'hop1_id':'citing_id', 'hop0_id':'cited_id', 'context':'citation_text'})
    h2_ctx = hop2[['hop2_id', 'hop1_id', 'citation_text']].copy().rename(columns={'hop2_id':'citing_id', 'hop1_id':'cited_id', 'context':'citation_text'})
    master_context = pd.concat([h1_ctx, h2_ctx]).dropna(subset=['citation_text']).drop_duplicates(subset=['citing_id', 'cited_id'])
    master_context.to_parquet("data/citation_contexts_scaled.parquet", index=False)
    with open("data/hop01_metadata_scaled.json", "w") as f: json.dump(papers, f)
    torch.save(data, "data/scicite_hetero_scaled.pt")
    print(f"🎉 All layers (0, 1, 2) mapped and saved!")

if __name__ == '__main__':
    main()
